# Generated by Django 2.1.2 on 2018-12-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_auto_20181209_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course_abbrv',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='course_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='department_courses.Class'),
        ),
        migrations.AlterField(
            model_name='post',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teacher_profile.Teacher_profile'),
        ),
    ]
