# Generated by Django 2.1.2 on 2018-12-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20181209_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='polyratings_post',
            field=models.BooleanField(default=False),
        ),
    ]
