# Generated by Django 2.1.2 on 2018-12-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_post_polyratings_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grade_received',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=2, null=True),
        ),
    ]
