# Generated by Django 2.1.2 on 2019-07-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_post_overall_rating_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overall_rating',
        ),
    ]
