# Generated by Django 2.1.2 on 2019-07-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_remove_post_overall_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nice_text',
            new_name='compact_text',
        ),
    ]
