# Generated by Django 2.1.2 on 2019-07-31 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_auto_20190727_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department_courses.Course'),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_abbrv',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='course_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='grade_received',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='quarter_taken',
            field=models.CharField(choices=[('Fall', 'Fall'), ('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6, null=True),
        ),
    ]
