# Generated by Django 2.1.2 on 2018-11-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0001_initial'),
        ('department_courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Class',
        ),
    ]
