# Generated by Django 2.1.2 on 2018-12-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_courses', '0002_auto_20181128_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='department',
        ),
        migrations.AddField(
            model_name='class',
            name='course_abbrv',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
