# Generated by Django 2.1.2 on 2018-12-14 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_courses', '0003_auto_20181209_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_abbrv',
        ),
        migrations.RemoveField(
            model_name='class',
            name='course_abbrv',
        ),
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department_courses.Department'),
        ),
    ]
