# Generated by Django 2.1.2 on 2018-12-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_courses', '0004_auto_20181214_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
