# Generated by Django 2.1.2 on 2018-12-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_courses', '0005_department_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
