# Generated by Django 2.1.2 on 2018-12-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('postings', '0003_auto_20181209_1937'),
        ('teacher_profile', '0005_auto_20181216_0911'),
        ('department_courses', '0006_class_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
    ]
