# Generated by Django 2.1.2 on 2018-12-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_courses', '0008_auto_20181216_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
