# Generated by Django 2.1.2 on 2019-07-31 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department_courses', '0010_auto_20190731_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_courses.Department'),
        ),
    ]
