# Generated by Django 2.1.2 on 2018-10-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(blank=True, max_length=60)),
                ('rating', models.CharField(default='n/a', max_length=3)),
                ('rating_num', models.IntegerField(blank=True, default=100)),
                ('difficulty_rating', models.IntegerField(null=True)),
                ('evaluations', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('total_overall_rating', models.IntegerField(default=0)),
                ('total_difficulty_rating', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_courses.Department')),
            ],
        ),
    ]
