# Generated by Django 2.1.2 on 2018-11-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_courses', '0002_auto_20181128_0432'),
        ('teacher_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='taught_classes',
            field=models.ManyToManyField(to='department_courses.Class'),
        ),
    ]
