# Generated by Django 2.1.2 on 2018-12-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0004_auto_20181209_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_profile',
            old_name='taught_classes',
            new_name='courses',
        ),
    ]
