# Generated by Django 2.1.2 on 2019-03-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0007_auto_20181224_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
