# Generated by Django 2.1.2 on 2019-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0008_auto_20190325_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_profile',
            name='rating_num',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
