# Generated by Django 2.1.2 on 2019-07-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0009_auto_20190726_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_profile',
            name='rating',
        ),
    ]
