# Generated by Django 2.1.2 on 2019-08-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0010_remove_teacher_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='overall_difficulty',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=4),
        ),
        migrations.AddField(
            model_name='teacher_profile',
            name='overall_rating',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=4),
        ),
    ]
