# Generated by Django 2.1.2 on 2019-08-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_profile', '0012_auto_20190801_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='evaluations',
            field=models.IntegerField(default=0),
        ),
    ]
